// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlo4fJaSRmEuWzlrkOoftw9koRypcnFiE',
    appId: '1:153270157924:web:a26a76c42cb298c231d571',
    messagingSenderId: '153270157924',
    projectId: 'diyet-takip-9d7ba',
    authDomain: 'diyet-takip-9d7ba.firebaseapp.com',
    storageBucket: 'diyet-takip-9d7ba.firebasestorage.app',
    measurementId: 'G-9CMBM2KHN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI0j7rwMl51SdzwVVBW5uldkaIo_KSmJk',
    appId: '1:153270157924:android:c94f4d4a814ceb7531d571',
    messagingSenderId: '153270157924',
    projectId: 'diyet-takip-9d7ba',
    storageBucket: 'diyet-takip-9d7ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJW0SvxH5Yrlxc7LHJCwGEVCnzhByvUnc',
    appId: '1:153270157924:ios:02592db4617b665131d571',
    messagingSenderId: '153270157924',
    projectId: 'diyet-takip-9d7ba',
    storageBucket: 'diyet-takip-9d7ba.firebasestorage.app',
    iosBundleId: 'com.example.diyetUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJW0SvxH5Yrlxc7LHJCwGEVCnzhByvUnc',
    appId: '1:153270157924:ios:02592db4617b665131d571',
    messagingSenderId: '153270157924',
    projectId: 'diyet-takip-9d7ba',
    storageBucket: 'diyet-takip-9d7ba.firebasestorage.app',
    iosBundleId: 'com.example.diyetUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlo4fJaSRmEuWzlrkOoftw9koRypcnFiE',
    appId: '1:153270157924:web:fd2d103f5dc53dfd31d571',
    messagingSenderId: '153270157924',
    projectId: 'diyet-takip-9d7ba',
    authDomain: 'diyet-takip-9d7ba.firebaseapp.com',
    storageBucket: 'diyet-takip-9d7ba.firebasestorage.app',
    measurementId: 'G-B7R4BCKT5N',
  );
}
